remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Norbert Waszkowiak
description: Wymagajcie od siebie choćby inni od was nie wymagali.
